### ISSUE TITLE
Links are inserted when copy/pasting action build logs and code with embedded links

### ISSUE THREAD

**Issue by xt0rted** [github/paste-markdown#49]
I was just trying to copy text out of an actions workflow, specifically [these lines](https://github.com/xt0rted-test/setup-dotnet-test/blob/044a4edc45952284fc730aed213e32644d07cb34/.github/workflows/dotnet-sdks.yml#L26-L32). Since I'm using OctoLinker the action name is linkified and the text that gets pasted into an issue shows up as:

```yml
- name: Set up .NET
        uses: https://github.com/actions/setup-dotnet/tree/v2.0.0v2.0.0
        with:
          dotnet-version: |
            3.1.417
            5.0.406
            6.0.201
```

instead of

```yml
      - name: Set up .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: |
            3.1.417
            5.0.406
            6.0.201
```

Similarly I tried to copy text out of an [Actions build log](https://github.com/xt0rted-test/setup-dotnet-test/runs/5973292245?check_suite_focus=true#step:2:22) and that's also pasting incorrectly. OctoLinker doesn't run on these pages so the issue isn't related to that like the above one kind of is.

```
.NET SDKs installed:
  3.1.120 [/usr/share/dotnet/sdk]
  3.1.202 [/usr/share/dotnet/sdk]
  3.1.[30](https://github.com/xt0rted-test/setup-dotnet-test/runs/5973292245?check_suite_focus=true#step:2:30)2 [/usr/share/dotnet/sdk]
  3.1.417 [/usr/share/dotnet/sdk]
  5.0.104 [/usr/share/dotnet/sdk]
  5.0.212 [/usr/share/dotnet/sdk]
  5.0.303 [/usr/share/dotnet/sdk]
  5.0.406 [/usr/share/dotnet/sdk]
  6.0.201 [/usr/share/dotnet/sdk]
```

In this example the 4th line should actually be:

```
3.1.302 [/usr/share/dotnet/sdk]
```
